import type { NextPage } from 'next'
import Head from 'next/head'
import { motion } from 'framer-motion'
import { useRef } from 'react'

const Home: NextPage = () => {
  const constraintsRef = useRef(null)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div></motion.div>
      <motion.div
        className="h-screen w-full flex items-center justify-center"
        ref={constraintsRef}
      >
        <motion.h1
          drag
          dragConstraints={constraintsRef}
          className="text-5xl w-fit"
        >
          Hello world!
        </motion.h1>
      </motion.div>
    </>
  )
}

export default Home
